from comptes.models import ProviderKind


PROVIDERS_MALI_VERSION = "2026-09-28"


PROVIDERS_MALI = [
    {
        "code": "CASH",
        "name": "Espèces",
        "official_name": "Espèces",
        "kind": ProviderKind.CASH,
        "country_code": "ML",
        "logo": "providers/ml/cash.svg",
        "active": True,
        "selectable": True,
        "sort_order": 10,
        "aliases": ["Caisse", "Cash"],
    },
    {
        "code": "BDM",
        "name": "BDM",
        "official_name": "Banque de Développement du Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/bdm.svg",
        "active": True,
        "selectable": True,
        "sort_order": 100,
        "aliases": ["Banque de Développement du Mali"],
    },
    {
        "code": "BIM",
        "name": "BIM",
        "official_name": "Banque Internationale pour le Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/bim.svg",
        "active": True,
        "selectable": True,
        "sort_order": 110,
        "aliases": ["Banque Internationale pour le Mali"],
    },
    {
        "code": "BNDA",
        "name": "BNDA",
        "official_name": "Banque Nationale de Développement Agricole",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/bnda.svg",
        "active": True,
        "selectable": True,
        "sort_order": 120,
        "aliases": ["Banque Nationale de Développement Agricole"],
    },
    {
        "code": "BCS",
        "name": "BCS",
        "official_name": "Banque Commerciale du Sahel",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/bcs.svg",
        "active": True,
        "selectable": True,
        "sort_order": 130,
        "aliases": ["Banque Commerciale du Sahel"],
    },
    {
        "code": "BOA_MALI",
        "name": "Bank of Africa",
        "official_name": "Bank of Africa - Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/boa.svg",
        "active": True,
        "selectable": True,
        "sort_order": 140,
        "aliases": ["BOA Mali", "Bank of Africa Mali"],
    },
    {
        "code": "AFG_MALI",
        "name": "AFG Bank Mali",
        "official_name": "AFG Bank Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/afg-bank.svg",
        "active": True,
        "selectable": True,
        "sort_order": 150,
        "aliases": ["BICI-M", "BICIM", "ex-BICI Mali"],
    },
    {
        "code": "BANQUE_ATLANTIQUE_MALI",
        "name": "Banque Atlantique",
        "official_name": "Banque Atlantique Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/banque-atlantique.svg",
        "active": True,
        "selectable": True,
        "sort_order": 160,
        "aliases": ["Banque Atlantique Mali", "BAM"],
    },
    {
        "code": "BMS",
        "name": "BMS",
        "official_name": "Banque Malienne de Solidarité",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/bms.svg",
        "active": True,
        "selectable": True,
        "sort_order": 170,
        "aliases": ["Banque Malienne de Solidarité"],
    },
    {
        "code": "BCI_MALI",
        "name": "BCI Mali",
        "official_name": "Banque pour le Commerce et l'Industrie du Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/bci.svg",
        "active": True,
        "selectable": True,
        "sort_order": 180,
        "aliases": ["Banque pour le Commerce et l'Industrie du Mali"],
    },
    {
        "code": "BSIC_MALI",
        "name": "BSIC Mali",
        "official_name": "Banque Sahélo-Saharienne pour l'Investissement et le Commerce - Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/bsic.svg",
        "active": True,
        "selectable": True,
        "sort_order": 190,
        "aliases": ["BSIC"],
    },
    {
        "code": "ECOBANK_MALI",
        "name": "Ecobank",
        "official_name": "Ecobank Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/ecobank.svg",
        "active": True,
        "selectable": True,
        "sort_order": 200,
        "aliases": ["Ecobank Mali"],
    },
    {
        "code": "CORIS_MALI",
        "name": "Coris Bank",
        "official_name": "Coris Bank International Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/coris-bank.svg",
        "active": True,
        "selectable": True,
        "sort_order": 210,
        "aliases": ["Coris Bank Mali"],
    },
    {
        "code": "UBA_MALI",
        "name": "UBA",
        "official_name": "United Bank for Africa - Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/uba.svg",
        "active": True,
        "selectable": True,
        "sort_order": 220,
        "aliases": ["UBA Mali", "United Bank for Africa Mali"],
    },
    {
        "code": "ORABANK_MALI",
        "name": "Orabank",
        "official_name": "Orabank Côte d'Ivoire, succursale du Mali",
        "kind": ProviderKind.BANK,
        "country_code": "ML",
        "logo": "providers/ml/banks/orabank.svg",
        "active": True,
        "selectable": True,
        "sort_order": 230,
        "aliases": ["Orabank Mali"],
    },
    {
        "code": "ORANGE_MONEY",
        "name": "Orange Money",
        "official_name": "Orange Finances Mobiles Mali",
        "kind": ProviderKind.MOBILE_MONEY,
        "country_code": "ML",
        "logo": "providers/ml/mobile-money/orange-money.svg",
        "active": True,
        "selectable": True,
        "sort_order": 300,
        "aliases": ["Orange", "OM"],
    },
    {
        "code": "MOOV_MONEY",
        "name": "Moov Money",
        "official_name": "BDM + Sotelma/Malitel",
        "kind": ProviderKind.MOBILE_MONEY,
        "country_code": "ML",
        "logo": "providers/ml/mobile-money/moov-money.svg",
        "active": True,
        "selectable": True,
        "sort_order": 310,
        "aliases": ["Moov", "Malitel Money"],
    },
    {
        "code": "WIZALL",
        "name": "Wizall",
        "official_name": "Banque Atlantique Mali + Wizall",
        "kind": ProviderKind.MOBILE_MONEY,
        "country_code": "ML",
        "logo": "providers/ml/mobile-money/wizall.svg",
        "active": True,
        "selectable": True,
        "sort_order": 320,
        "aliases": [],
    },
    {
        "code": "ZELIA",
        "name": "Zelia",
        "official_name": "BSIC Mali + Zelia Gold Solutions",
        "kind": ProviderKind.MOBILE_MONEY,
        "country_code": "ML",
        "logo": "providers/ml/mobile-money/zelia.svg",
        "active": True,
        "selectable": True,
        "sort_order": 330,
        "aliases": [],
    },
    {
        "code": "CORIS_MONEY",
        "name": "Coris Money",
        "official_name": "Coris Bank Mali + M2I",
        "kind": ProviderKind.MOBILE_MONEY,
        "country_code": "ML",
        "logo": "providers/ml/mobile-money/coris-money.svg",
        "active": True,
        "selectable": True,
        "sort_order": 340,
        "aliases": [],
    },
    {
        "code": "SAMA_MONEY",
        "name": "Sama Money",
        "official_name": "Sama Money SA",
        "kind": ProviderKind.MOBILE_MONEY,
        "country_code": "ML",
        "logo": "providers/ml/mobile-money/sama-money.svg",
        "active": True,
        "selectable": True,
        "sort_order": 350,
        "aliases": ["Sama"],
    },
    {
        "code": "WAVE",
        "name": "Wave",
        "official_name": "Orabank Mali + Wave",
        "kind": ProviderKind.MOBILE_MONEY,
        "country_code": "ML",
        "logo": "providers/ml/mobile-money/wave.svg",
        "active": True,
        "selectable": True,
        "sort_order": 360,
        "aliases": [],
    },
    {
        "code": "T_LIA",
        "name": "T-LIA",
        "official_name": "BICIM Mali + T-LIA",
        "kind": ProviderKind.MOBILE_MONEY,
        "country_code": "ML",
        "logo": "providers/ml/mobile-money/t-lia.svg",
        "active": True,
        "selectable": False,
        "sort_order": 370,
        "aliases": ["TLIA"],
        "metadata": {"commercial_identity_check_recommended": True, "selection_disabled_reason": "Vérification réglementaire/commerciale requise"},
    },
    {
        "code": "OPTIMA",
        "name": "Optima",
        "official_name": "BICIM Mali + Optima",
        "kind": ProviderKind.MOBILE_MONEY,
        "country_code": "ML",
        "logo": "providers/ml/mobile-money/optima.svg",
        "active": True,
        "selectable": False,
        "sort_order": 380,
        "aliases": [],
        "metadata": {"commercial_identity_check_recommended": True, "selection_disabled_reason": "Vérification réglementaire/commerciale requise"},
    },
    {
        "code": "INTOUCH_MALI",
        "name": "InTouch Mali",
        "official_name": "InTouch Mali",
        "kind": ProviderKind.PAYMENT_INSTITUTION,
        "country_code": "ML",
        "logo": "",
        "active": True,
        "selectable": False,
        "sort_order": 500,
        "aliases": ["InTouch"],
    },
    {
        "code": "CAURIDOR",
        "name": "Cauridor",
        "official_name": "Cauridor",
        "kind": ProviderKind.PAYMENT_INSTITUTION,
        "country_code": "ML",
        "logo": "",
        "active": True,
        "selectable": False,
        "sort_order": 510,
        "aliases": [],
    },
]
