# Generated by Django 5.2.11 on 2026-08-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_devise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={'ordering': ['code'], 'permissions': [('encaisser', 'Peut encaisser sur un compte'), ('decaisser', 'Peut décaisser depuis un compte'), ('transferer', 'Peut transférer entre comptes'), ('annuler', 'Peut annuler un mouvement'), ('cloturer', 'Peut clôturer un compte'), ('rapprocher', 'Peut rapprocher un compte')], 'verbose_name': 'Compte financier', 'verbose_name_plural': 'Comptes financiers'},
        ),
        migrations.AlterField(
            model_name='mouvementcompte',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='comptes.compte', verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='transfertcompte',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='comptes.compte', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='transfertcompte',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='comptes.compte', verbose_name='Source'),
        ),
    ]
