# Generated by Django 5.2.11 on 2026-08-08 18:46

import comptes.defaults
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_compte_options_alter_mouvementcompte_compte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='devise',
            field=models.ForeignKey(db_column='devise', default=comptes.defaults.default_currency, on_delete=django.db.models.deletion.PROTECT, related_name='comptes', to='comptes.devise', to_field='code', verbose_name='Devise'),
        ),
    ]
