# Generated by Django 6.0.8 on 2026-09-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_alter_compte_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='entreprise_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='compte',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AlterUniqueTogether(
            name='compte',
            unique_together={('entreprise_id', 'code')},
        ),
    ]
