# Generated by Codex on 2026-09-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comptes", "0005_compte_entreprise_id_alter_compte_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialProvider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=80, unique=True, verbose_name="Code")),
                ("name", models.CharField(max_length=120, verbose_name="Nom affiché")),
                ("official_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Nom officiel")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CASH", "Espèces"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK", "Banque"),
                            ("PAYMENT_INSTITUTION", "Établissement de paiement"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Famille",
                    ),
                ),
                ("country_code", models.CharField(db_index=True, max_length=2, verbose_name="Pays")),
                ("logo", models.CharField(blank=True, default="", max_length=255, verbose_name="Logo")),
                ("active", models.BooleanField(default=True, verbose_name="Actif")),
                ("selectable", models.BooleanField(default=True, verbose_name="Sélectionnable")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("aliases", models.JSONField(blank=True, default=list, verbose_name="Alias")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Métadonnées")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fournisseur financier",
                "verbose_name_plural": "Fournisseurs financiers",
                "ordering": ["country_code", "sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="compte",
            name="identifiant",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Numéro de téléphone, numéro de compte bancaire ou libellé libre.",
                max_length=120,
                verbose_name="Identifiant du compte",
            ),
        ),
        migrations.AddField(
            model_name="compte",
            name="accepte_ventes",
            field=models.BooleanField(
                default=True,
                help_text="Compte proposé lors d'un encaissement de vente.",
                verbose_name="Accepte les ventes",
            ),
        ),
        migrations.AddField(
            model_name="compte",
            name="par_defaut",
            field=models.BooleanField(default=False, verbose_name="Compte par défaut"),
        ),
        migrations.AddField(
            model_name="compte",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comptes",
                to="comptes.financialprovider",
                verbose_name="Fournisseur financier",
            ),
        ),
        migrations.AddIndex(
            model_name="financialprovider",
            index=models.Index(
                fields=["country_code", "kind", "active", "selectable"],
                name="comptes_fin_country_def98c_idx",
            ),
        ),
    ]
