# Generated by Django 5.2.11 on 2026-09-27 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_financial_provider_compte_provider'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModePaiementCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorite', models.PositiveIntegerField(default=0, verbose_name='Priorité')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lien mode de paiement / compte',
                'verbose_name_plural': 'Liens modes de paiement / comptes',
                'ordering': ['priorite', 'id'],
            },
        ),
        migrations.AddField(
            model_name='modepaiement',
            name='entreprise_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mouvementcompte',
            name='entreprise_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mouvementcompte',
            name='payload_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='mouvementcompte',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='mouvementcompte',
            name='source_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='mouvementcompte',
            name='source_system',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='mouvementcompte',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='transfertcompte',
            name='entreprise_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transfertcompte',
            name='payload_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='code',
            field=models.CharField(help_text='Identifiant métier libre, par exemple ESPECES ou ORANGE_MONEY.', max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='mouvementcompte',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Clé fournie par le système appelant pour éviter une double opération.', max_length=128, null=True, verbose_name="Clé d'idempotence"),
        ),
        migrations.AlterField(
            model_name='transfertcompte',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Clé d'idempotence"),
        ),
        migrations.AddIndex(
            model_name='mouvementcompte',
            index=models.Index(fields=['entreprise_id', 'date'], name='comptes_mou_entrepr_4abf33_idx'),
        ),
        migrations.AddConstraint(
            model_name='mouvementcompte',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('entreprise_id', 'idempotency_key'), name='mouvement_idempotence_par_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='transfertcompte',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('entreprise_id', 'idempotency_key'), name='transfert_idempotence_par_entreprise'),
        ),
        migrations.AddField(
            model_name='modepaiementcompte',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_modes_paiement', to='comptes.compte', verbose_name='Compte'),
        ),
        migrations.AddField(
            model_name='modepaiementcompte',
            name='mode_paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_comptes', to='comptes.modepaiement', verbose_name='Mode de paiement'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='modepaiement',
                    name='comptes',
                    field=models.ManyToManyField(blank=True, help_text='Comptes sur lesquels ce mode de paiement peut être encaissé.', related_name='modes_paiement', through='comptes.ModePaiementCompte', to='comptes.compte', verbose_name='Comptes liés'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddConstraint(
            model_name='modepaiement',
            constraint=models.UniqueConstraint(fields=('entreprise_id', 'code'), name='mode_paiement_unique_par_entreprise'),
        ),
        migrations.AddConstraint(
            model_name='modepaiementcompte',
            constraint=models.UniqueConstraint(fields=('mode_paiement', 'compte'), name='mode_paiement_compte_unique'),
        ),
    ]
